In [1]:
a = 10

In [3]:
b = 20


In [4]:
for i in range(1, 10):
    print(i)

1
2
3
4
5
6
7
8
9


In [5]:
# 1) Numpy
# 2) Pandas
# 3) Matplotlib

In [6]:
# Numpy : Numarical Python

# arrays

In [7]:
# list = [12, "hlo", ]    python

# numpy :  [12, 10, 78, 10]   python + c
# 50x


# 2005


In [ ]:
# Numpy : 

# objects ==== > array

# ndarray

In [8]:
!pip install numpy

In [9]:
import numpy

In [10]:
arr = numpy.array(12)

In [16]:
arr.ndim

0

In [11]:
type(arr)

numpy.ndarray

In [12]:
import numpy as np

In [13]:
x = np.array([1, 2, 3, 4, 6])

In [14]:
x

array([1, 2, 3, 4, 6])

In [15]:
x.ndim

1

In [21]:
x1 = np.array([[1, 2, 3], [4, 5, 6]])

In [22]:
x1

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
x1.ndim

2

In [27]:
x3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [28]:
x3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [29]:
x3.ndim

3

In [30]:
# indexing : 

In [32]:
a = np.array([1, 2, 3, 4, 6, 4, 10])

In [33]:
a

array([ 1,  2,  3,  4,  6,  4, 10])

In [35]:
a[2] + a[3]

7

In [37]:
b = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [38]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [43]:
b[0][3]

4

In [44]:
x3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [46]:
x3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [49]:
x3[1][0][1]

8

In [50]:
# slicing : 

# [start : end : increment]

# default :::::;
# start = 0
# end = n - 1
# increment = 1

In [51]:
a = np.array([1, 2, 3, 4, 6, 4, 10])

In [52]:
a[1 : 5 : 1]

array([2, 3, 4, 6])

In [53]:
a[2 :]

array([ 3,  4,  6,  4, 10])

In [54]:
a[:5]

array([1, 2, 3, 4, 6])

In [55]:
a = np.array([1, 2, 3, 4, 6, 4, 10])

In [57]:
a[::-1]

array([10,  4,  6,  4,  3,  2,  1])