In [1]:
# Numpy : 

In [2]:
from numpy import random
import numpy as np

In [7]:
# randint

x = random.randint(100)

In [8]:
x

79

In [13]:
y = random.rand()

In [14]:
y

0.6791067407510102

In [22]:
zx = random.randint(200, size = (2, 10))

In [23]:
zx

array([[110,  43,  35,  28,  45, 193,  49,  30,  63,  80],
       [194,  24,  35, 117,  38,  82,  98, 126,   8,  49]])

In [52]:
q = random.choice([2, 3, 5, 6, 19], size = (2, 10), p = [0.5, 0.1, 0.2, 0.1, 0.1])

In [53]:
q

array([[19,  2,  2,  5, 19,  5,  2,  3,  2,  6],
       [ 5,  2,  2,  2, 19,  2,  5,  2,  5,  5]])

In [54]:
# zx = random.randint(100, size = 10)

In [70]:
zx = np.array([1, 2, 3, 4, 5, 6, 7, 18])

In [73]:
random.shuffle(zx)

In [74]:
zx

array([18,  2,  3,  7,  6,  4,  5,  1])

In [75]:
a = np.array([1, 2, 3, 4, 5])

In [76]:
y = np.insert(a, range(1, len(a)), 0)

In [79]:
y = np.array([])

In [86]:
for i in a:
    print(i)
    np.append(y, i)

1
2
3
4
5


In [87]:
e

array([5.])