In [ ]:
# Numpy : 

In [ ]:
# ndarry
# objects
# indexing
# 1d 2d, 3d
# slicing

In [1]:
import numpy as np

In [27]:
x = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]])

In [28]:
x.shape

(2, 2, 4)

In [29]:
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [6]:
x.ndim

3

In [10]:
x[1][0][1 : 4]

array([10, 11, 12])

In [12]:
# sort()

x = np.array([3, 4, 5, 2, 3, 6, 2, 4, 7, 3, 8, 12, 5, 6, 10])

In [13]:
x

array([ 3,  4,  5,  2,  3,  6,  2,  4,  7,  3,  8, 12,  5,  6, 10])

In [15]:
y = np.sort(x)

In [16]:
y[::-1]

array([12, 10,  8,  7,  6,  6,  5,  5,  4,  4,  3,  3,  3,  2,  2])

In [19]:
# where

x = np.array([3, 4, 5, 2, 3, 8, 6, 2, 4, 7, 3, 8, 12, 5, 6, 8, 10])

In [20]:
np.where(x == 8)

(array([ 5, 11, 15], dtype=int64),)

In [21]:
# shape : return the shape of an ndarry

x = np.array([3, 4, 5, 2, 3, 8, 6, 2, 4, 7, 3, 8, 12, 5, 6, 8, 10])

In [22]:
x.shape

(17,)

In [24]:
y = np.array([[1, 2, 3, 4], [6, 7, 8, 9]])

In [25]:
y.shape

(2, 4)

In [26]:
y

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [36]:
# reshape
x = np.array([3, 4, 5, 2, 3, 8, 6, 2, 4, 7, 3, 8, 12, 5, 6, 8, 10, 18])

In [37]:
len(x)

18

In [47]:
z = x.reshape((3, 6))

In [48]:
z

array([[ 3,  4,  5,  2,  3,  8],
       [ 6,  2,  4,  7,  3,  8],
       [12,  5,  6,  8, 10, 18]])

In [49]:
# concatenate

In [50]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

In [56]:
c = a + b

In [57]:
c

array([ 7,  9, 11, 13, 15])

In [58]:
zx = np.concatenate((a, b))

In [59]:
zx

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
k = np.vstack((a, b))

In [62]:
k

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
# random 
