In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("heart.csv")

In [3]:
data

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           NaN        140          289          0  NormalATA   
1     49   F           NAP        160          180          0     Normal   
2     37   M           ATA        130          283          0         ST   
3     48   F           ASY        138          214          0     Normal   
4     54   M           NAP        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Sex             918 non-null    object 
 2   ChestPainType   917 non-null    object 
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    object 
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    object 
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object 
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB


In [5]:
data.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           NaN        140          289          0  NormalATA    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
lbe = LabelEncoder()

In [8]:
zx = ["hlo", "apple", "banana", "orange", "banana", "banana", "hlo"]

In [9]:
er = lbe.fit_transform(zx)

In [10]:
er

array([2, 0, 1, 3, 1, 1, 2], dtype=int64)

In [12]:
data["Sex"] = lbe.fit_transform(data["Sex"])

In [13]:
data

Age  Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40    1           NaN        140          289          0  NormalATA   
1     49    0           NAP        160          180          0     Normal   
2     37    1           ATA        130          283          0         ST   
3     48    0           ASY        138          214          0     Normal   
4     54    1           NAP        150          195          0     Normal   
..   ...  ...           ...        ...          ...        ...        ...   
913   45    1            TA        110          264          0     Normal   
914   68    1           ASY        144          193          1     Normal   
915   57    1           ASY        130          131          0     Normal   
916   57    0           ATA        130          236          0        LVH   
917   38    1           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [17]:
data["ChestPainType"] = lbe.fit_transform(data["ChestPainType"])
data["RestingECG"] = lbe.fit_transform(data["RestingECG"])
data["ExerciseAngina"] = lbe.fit_transform(data["ExerciseAngina"])
data["ST_Slope"] = lbe.fit_transform(data["ST_Slope"])

In [18]:
data

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0     40    1              4        140          289          0           2   
1     49    0              2        160          180          0           1   
2     37    1              1        130          283          0           3   
3     48    0              0        138          214          0           1   
4     54    1              2        150          195          0           1   
..   ...  ...            ...        ...          ...        ...         ...   
913   45    1              3        110          264          0           1   
914   68    1              0        144          193          1           1   
915   57    1              0        130          131          0           1   
916   57    0              1        130          236          0           0   
917   38    1              2        138          175          0           1   

     MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0      172               0      0.0         2             0  
1      156               0      1.0         1             1  
2       98               0      0.0         2             0  
3      108               1      1.5         1             1  
4      122               0      0.0         2             0  
..     ...             ...      ...       ...           ...  
913    132               0      1.2         1             1  
914    141               0      3.4         1             1  
915    115               1      1.2         1             1  
916    174               0      0.0         1             1  
917    173               0      0.0         2             0  

[918 rows x 12 columns]

In [19]:
data.head()

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0   40    1              4        140          289          0           2   
1   49    0              2        160          180          0           1   
2   37    1              1        130          283          0           3   
3   48    0              0        138          214          0           1   
4   54    1              2        150          195          0           1   

   MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0    172               0      0.0         2             0  
1    156               0      1.0         1             1  
2     98               0      0.0         2             0  
3    108               1      1.5         1             1  
4    122               0      0.0         2             0

In [20]:
x = data.drop(columns="HeartDisease")
y = data["HeartDisease"]

In [22]:
x


Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0     40    1              4        140          289          0           2   
1     49    0              2        160          180          0           1   
2     37    1              1        130          283          0           3   
3     48    0              0        138          214          0           1   
4     54    1              2        150          195          0           1   
..   ...  ...            ...        ...          ...        ...         ...   
913   45    1              3        110          264          0           1   
914   68    1              0        144          193          1           1   
915   57    1              0        130          131          0           1   
916   57    0              1        130          236          0           0   
917   38    1              2        138          175          0           1   

     MaxHR  ExerciseAngina  Oldpeak  ST_Slope  
0      172               0      0.0         2  
1      156               0      1.0         1  
2       98               0      0.0         2  
3      108               1      1.5         1  
4      122               0      0.0         2  
..     ...             ...      ...       ...  
913    132               0      1.2         1  
914    141               0      3.4         1  
915    115               1      1.2         1  
916    174               0      0.0         1  
917    173               0      0.0         2  

[918 rows x 11 columns]

In [23]:
x.shape

(918, 11)

In [24]:
y.shape

(918,)

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 20, test_size = 0.2)

In [28]:
x_train.shape

(734, 11)

In [29]:
from sklearn.linear_model import LogisticRegression

In [30]:
mdl = LogisticRegression()

In [31]:
mdl.fit(x_train, y_train)

C:\Users\programography\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [32]:
from sklearn.metrics import accuracy_score

In [33]:
x_test

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
358   38    1              2        115            0          0           1   
333   40    1              0         95            0          1           3   
13    49    1              0        140          234          0           1   
364   56    1              2        120            0          0           1   
204   56    1              1        130          184          0           1   
..   ...  ...            ...        ...          ...        ...         ...   
867   44    1              0        112          290          0           0   
739   54    1              2        125          273          0           0   
422   65    1              0        150          236          1           3   
668   63    0              1        140          195          0           1   
440   52    1              2        128            0          0           3   

     MaxHR  ExerciseAngina  Oldpeak  ST_Slope  
358    128               1      0.0         1  
333    144               0      0.0         2  
13     140               1      1.0         1  
364     97               0      0.0         1  
204    100               0      0.0         2  
..     ...             ...      ...       ...  
867    153               0      0.0         2  
739    152               0      0.5         0  
422    105               1      0.0         1  
668    179               0      0.0         2  
440    180               0      3.0         2  

[184 rows x 11 columns]

In [35]:
y_pred = mdl.predict(x_test)

In [36]:
y_pred

array([1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0], dtype=int64)

In [37]:
y_test

358    1
333    1
13     1
364    0
204    0
      ..
867    1
739    0
422    1
668    0
440    1
Name: HeartDisease, Length: 184, dtype: int64

In [38]:
accuracy_score(y_pred, y_test)

0.8532608695652174

In [40]:
data.head()

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0   40    1              4        140          289          0           2   
1   49    0              2        160          180          0           1   
2   37    1              1        130          283          0           3   
3   48    0              0        138          214          0           1   
4   54    1              2        150          195          0           1   

   MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0    172               0      0.0         2             0  
1    156               0      1.0         1             1  
2     98               0      0.0         2             0  
3    108               1      1.5         1             1  
4    122               0      0.0         2             0

In [69]:
dt = (40, 1, 2, 140, 289, 0, 2, 172, 0, 0.0, 2)

In [70]:
# mdl.predict(dt)

arr = np.asarray(dt)
arr

array([ 40.,   1.,   2., 140., 289.,   0.,   2., 172.,   0.,   0.,   2.])

In [71]:
yu = arr.reshape(-1, 1)

In [72]:
yu

array([[ 40.],
       [  1.],
       [  2.],
       [140.],
       [289.],
       [  0.],
       [  2.],
       [172.],
       [  0.],
       [  0.],
       [  2.]])

In [79]:
mdl.predict(yu.reshape(-1, 1))

C:\Users\programography\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


ValueError: X has 1 features, but LogisticRegression is expecting 11 features as input.

In [80]:
import joblib

In [81]:
joblib.dump(mdl, "heart_decisis_prediction.joblib")

['heart_decisis_prediction.joblib']