In [1]:
# Numpy : 
# 1) Fancy indexing
# 2) Boolean indexing

In [2]:
import numpy as np

In [20]:
x = np.random.randint(2, 15, size = (5, 6))

In [21]:
x

array([[ 9,  7, 12,  6, 12,  9],
       [ 6,  8, 14, 11,  4,  9],
       [ 2, 11,  7,  6, 12, 12],
       [11, 12,  8, 12,  7, 11],
       [ 3,  2,  3, 14,  3,  2]])

In [22]:
x > 10

array([[False, False,  True, False,  True, False],
       [False, False,  True,  True, False, False],
       [False,  True, False, False,  True,  True],
       [ True,  True, False,  True, False,  True],
       [False, False, False,  True, False, False]])

In [23]:
x[x>10]

array([12, 12, 14, 11, 11, 12, 12, 11, 12, 12, 11, 14])

In [27]:
x[~(x % 2 == 0)]

array([ 9,  7,  9, 11,  9, 11,  7, 11,  7, 11,  3,  3,  3])

In [28]:
x

array([[ 9,  7, 12,  6, 12,  9],
       [ 6,  8, 14, 11,  4,  9],
       [ 2, 11,  7,  6, 12, 12],
       [11, 12,  8, 12,  7, 11],
       [ 3,  2,  3, 14,  3,  2]])

In [34]:
x[(x > 10) & (x % 2 == 0)]

array([12, 12, 14, 12, 12, 12, 12, 14])

In [35]:
# arange

In [38]:
# y = np.arange(strat, end, increment)

y = np.arange(3, 20, 1)

In [39]:
y

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
3    5 