In [ ]:
Numpy : 

In [ ]:
ndarray : 
ndim
shape
where()
sort()
indxing
slicing
append()
insert()
delete()
creating ndarray:::
    1-D ----- 4-D
zeros
ones

# np. 

In [ ]:
# reshape()

In [8]:
import numpy as np

xyz = np.array([12, 34, 5, 67, 87, 90, 45, 34, 23, 5, 23, 45, 3, 34])

In [9]:
xyz.shape

(14,)

In [10]:
xyz.ndim

1

In [11]:
xyz

array([12, 34,  5, 67, 87, 90, 45, 34, 23,  5, 23, 45,  3, 34])

In [12]:
len(xyz)

14

### convert 1-D to 2-D

In [14]:
qw = xyz.reshape(2, 7)

In [15]:
qw

array([[12, 34,  5, 67, 87, 90, 45],
       [34, 23,  5, 23, 45,  3, 34]])

In [16]:
qw.ndim

2

In [17]:
xyz.reshape(7, 2)

array([[12, 34],
       [ 5, 67],
       [87, 90],
       [45, 34],
       [23,  5],
       [23, 45],
       [ 3, 34]])

In [19]:
xyz.reshape(14, 1)

array([[12],
       [34],
       [ 5],
       [67],
       [87],
       [90],
       [45],
       [34],
       [23],
       [ 5],
       [23],
       [45],
       [ 3],
       [34]])

In [20]:
xy = np.arange(1, 21)

In [21]:
xy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [23]:
xy.reshape(5, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [24]:
# np.reshape(objectname, respae)

In [26]:
np.reshape(xy, (2, 10))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [27]:
# -1 -> 

In [28]:
xy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
xy.reshape(5, -1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [30]:
xy.reshape(-1, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

### 2D to 1D

In [31]:
zx = np.array([[34, 23, 45, 23], [45, 56, 34, 23]])

In [33]:
zx

array([[34, 23, 45, 23],
       [45, 56, 34, 23]])

In [34]:
zx.shape

(2, 4)

In [35]:
zx.ndim

2

In [37]:
zx.reshape(-1)

array([34, 23, 45, 23, 45, 56, 34, 23])

In [38]:
# 1-D to 3-D

In [41]:
zx = np.arange(1, 19)

In [42]:
zx

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [44]:
zx.reshape(3, 3, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [45]:
# random

In [46]:
# import random

In [47]:
from numpy import random

In [48]:
# randint() ::: it returns a random number from the given range


In [55]:
random.randint(2, 80)

28

In [56]:
a = random.randint(2, 80, size = (10))

In [57]:
a

array([ 8, 53, 11, 23, 39, 62, 66, 23, 53, 54])

In [58]:
a = random.randint(2, 80, size = (3, 6))

In [59]:
a

array([[35, 55, 19, 42, 74,  9],
       [18, 72, 48, 20, 63, 55],
       [72, 53,  8, 18, 64, 44]])

In [60]:
a = random.randint(2, 80, size = (3, 6, 3))

In [61]:
a

array([[[62, 43, 40],
        [25, 14, 75],
        [40, 36,  8],
        [24, 63, 43],
        [51, 40, 50],
        [51, 15, 67]],

       [[22, 72,  5],
        [ 2, 25, 13],
        [47, 45, 40],
        [35, 75,  2],
        [21, 73, 56],
        [39, 69, 64]],

       [[37, 34,  8],
        [58, 19, 49],
        [39, 49, 14],
        [ 4, 29, 50],
        [32, 13, 16],
        [37, 47, 30]]])

In [62]:
# rand() ---> it returns a random element betweem 0 to 1

In [68]:
random.rand()

0.14588874215214576

In [73]:
c = random.rand(4)

In [74]:
c

array([0.71773714, 0.38766792, 0.21279652, 0.26500294])

In [75]:
c = random.rand(4, 4)
c

array([[0.44981311, 0.06923416, 0.99313998, 0.72528083],
       [0.82749327, 0.34425148, 0.2847134 , 0.02944738],
       [0.13346827, 0.86053175, 0.66324528, 0.94993597],
       [0.28347429, 0.24239672, 0.12618078, 0.42935944]])

In [76]:
# randint()
# rand()

In [77]:
# choice  -> 

In [93]:
zx = random.choice([2, 4, 6, 8, 5, 9, 3])

In [94]:
zx

5

In [97]:
zx = random.choice([2, 4, 6, 8, 5, 9, 3], size = (5, 9))

In [98]:
zx

array([[2, 5, 5, 5, 6, 2, 8, 9, 4],
       [9, 8, 5, 3, 2, 5, 6, 4, 6],
       [2, 2, 2, 4, 6, 9, 2, 8, 5],
       [3, 9, 4, 9, 5, 3, 3, 3, 8],
       [4, 9, 9, 2, 2, 9, 2, 2, 8]])

In [99]:
# random.shuffle

In [101]:
zx = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
random.shuffle(zx)

In [103]:
zx

array([7, 1, 2, 9, 5, 3, 8, 4, 6])

In [ ]:
random:
    randint
    rand
    shuffle
    choice