In [1]:
import numpy as np

In [2]:
# Indexing / slicing in numpy

In [3]:
zx = np.array([12, 34, 56, 67, 89])

In [4]:
zx

array([12, 34, 56, 67, 89])

In [5]:
# replace elements from ndarray::::::

# objectname[indexnumber] = newelemnt

In [6]:
zx[3] = 100

In [7]:
zx


array([ 12,  34,  56, 100,  89])

In [8]:
x = np.array([23, 45, 56, 78, 5, 34, 23, 2, 45, 23])

In [9]:
x[4] = 500

In [10]:
x

array([ 23,  45,  56,  78, 500,  34,  23,   2,  45,  23])

In [11]:
x = np.array([23, 45, 56, 78, 5, 34, 23, 2, 45, 23])

In [12]:
indexe = [1, 4, -3]
newlement = [100, 500, 200]

In [13]:
x[indexe] = newlement

In [14]:
x

array([ 23, 100,  56,  78, 500,  34,  23, 200,  45,  23])

## Adding new element in ndarray

In [ ]:
list : 
    

In [15]:
z = [12, 34, 45, 23, 45]


In [17]:
z.insert(1, 100)

In [18]:
z

[12, 100, 34, 45, 23, 45]

In [19]:
xy = np.array([12, 34, 45, 67, 34, 78, 4])

In [21]:
# append()

# syntxt :
    # np.append(objectname, newelemtn)

In [24]:
wq = np.append(xy, 1000)

In [25]:
wq

array([  12,   34,   45,   67,   34,   78,    4, 1000])

In [26]:
wq = np.append(xy, [12, 56, 34, 67, 34, 67, 34])

In [28]:
wq

array([12, 34, 45, 67, 34, 78,  4, 12, 56, 34, 67, 34, 67, 34])

In [29]:
# insert()

In [30]:
xy = np.array([12, 34, 45, 67, 34, 78, 4])

In [31]:
# np.insert(objename, indexnumber, newelement)

In [32]:
np.insert(xy, 2, 1000)

array([  12,   34, 1000,   45,   67,   34,   78,    4])

In [33]:
# delete()

In [34]:
xy = np.array([12, 34, 45, 67, 34, 78, 4])

In [38]:
# np.delete(objectname, indexnumber)

np.delete(xy, 1)

array([12, 45, 67, 34, 78,  4])

In [40]:
# x = np.array()

In [ ]:
array(['2 x 1 = 2', '2 x 2 = 4', ......., '2 x 10 = 20'])

In [41]:
np.arange(12, 30)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29])

In [44]:
table = np.array([])

for i in np.arange(1, 11):
    table = np.append(table, f"2 x {i} = {2*i}")

In [45]:
table

array(['2 x 1 = 2', '2 x 2 = 4', '2 x 3 = 6', '2 x 4 = 8', '2 x 5 = 10',
       '2 x 6 = 12', '2 x 7 = 14', '2 x 8 = 16', '2 x 9 = 18',
       '2 x 10 = 20'], dtype='<U32')

In [46]:
# numpy : 

In [47]:
# sort() -> arrays sorting

In [48]:
xyz = np.array([23, 45, 67, 45, 3, 5, 6, 8, 3])

In [50]:
qw = np.sort(xyz)

In [51]:
qw

array([ 3,  3,  5,  6,  8, 23, 45, 45, 67])

In [52]:
qw[::-1]

array([67, 45, 45, 23,  8,  6,  5,  3,  3])

In [53]:
# where() -> it returns the index number a perticuler element

In [56]:
xyz = np.array([23, 45, 67, 45, 3, 5, 6, 8, 3, 54, 67, 4, 6, 7, 8, 5, 34, 56])

In [55]:
# np.where(objectnme == element)

In [57]:
np.where(xyz == 23)

(array([0], dtype=int64),)

In [59]:
np.where(xyz == 5)

(array([ 5, 15], dtype=int64),)

In [64]:
# np.where(xyz < 10)

In [66]:
# zeros -> help us to genrate zeries

In [70]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [71]:
# onces

In [72]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [73]:
help(np.any)

Help on _ArrayFunctionDispatcher in module numpy:

any(a, axis=None, out=None, keepdims=<no value>, *, where=<no value>)
    Test whether any array element along a given axis evaluates to True.

    Returns single boolean if `axis` is ``None``

    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a logical OR reduction is performed.
        The default (``axis=None``) is to perform a logical OR over all
        the dimensions of the input array. `axis` may be negative, in
        which case it counts from the last to the first axis.

        .. versionadded:: 1.7.0

        If this is a tuple of ints, a reduction is performed on multiple
        axes, instead of a single axis or all the axes as before.
    out : ndarray, optional
        Alternate output array in which to place the result.  It must have
        the same shape as the expected ou