In [ ]:
Numpy : numarical python

Array's      list

In [ ]:
list ---> slow..
    python, 
    hitrogenious type of data.....

lst = [10, 20, "hlo", "car", True]



In [1]:
# arrays -> is a data structur, which hold the homogenious type data, in the congeious mamory location.

In [ ]:
arrays:

numpy : 2005
     Travis Oliphant   

2) 70% => python
    30% => C / C#

numpy 50x as compere to list..

In [2]:
!pip install numpy

DEPRECATION: textract 1.6.5 has a non-standard dependency specifier extract-msg<=0.29.*. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of textract or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063


In [3]:
import numpy as np

In [ ]:
# numpy ------------> ndarrays

## Ndarrays

In [ ]:
n-dimestional arrays....

in numpy, when we create an object with the help of array method, that object is called ndarray.

In [4]:
arr = np.array(10)

In [5]:
arr

array(10)

In [6]:
type(arr)

numpy.ndarray

In [ ]:
arrays : 
    0 - D
    1 - D



    n - D

In [7]:
# ndim

In [8]:
arr.ndim

0

In [9]:
# 1 - D Ndarray

In [10]:
arr1 = np.array([12, 34, 45, 67, 78])

In [11]:
type(arr1)

numpy.ndarray

In [12]:
arr1

array([12, 34, 45, 67, 78])

In [13]:
arr1.ndim

1

In [20]:
xyz = np.array([[12, 34, 45, 66], [45, 56, 67, 89], [45, 67, 78, 89]])

In [21]:
xyz

array([[12, 34, 45, 66],
       [45, 56, 67, 89],
       [45, 67, 78, 89]])

In [22]:
xyz.ndim

2

In [29]:
abc = np.array([[[12, 34, 56], [45, 56, 67]], [[34, 56, 67], [56, 67, 87]]])

In [30]:
abc

array([[[12, 34, 56],
        [45, 56, 67]],

       [[34, 56, 67],
        [56, 67, 87]]])

In [31]:
abc.ndim

3

In [32]:
xyz = np.array([[[[[[[[[[12]]]]]]]]]])

In [33]:
xyz.ndim

10

In [34]:
# shape : return ....

In [35]:
a = np.array([34, 545, 67, 78, 23])

In [36]:
a

array([ 34, 545,  67,  78,  23])

In [37]:
a.shape

(5,)

In [42]:
xyz = np.array([[34, 45, 5, 45, 34], [45, 56, 67, 78, 45]])

In [43]:
xyz

array([[34, 45,  5, 45, 34],
       [45, 56, 67, 78, 45]])

In [44]:
xyz.shape

(2, 5)

In [45]:
abc = np.array([[[12, 34, 56], [45, 56, 67]], [[34, 56, 67], [56, 67, 87]]])

In [46]:
abc.shape

(2, 2, 3)

In [ ]:
numpy
ndarray
careate ndarray
    1-d
    2-d
    3-d
ndim
shape