In [1]:
# Numpy : 

In [2]:
# ndarrays : 

In [3]:
import numpy as np

In [4]:
arr = np.array([12, 34, 45, 56, 78, 45, 34])

In [5]:
arr

array([12, 34, 45, 56, 78, 45, 34])

In [6]:
arr.shape

(7,)

In [7]:
arr.ndim

1

In [8]:
# 4-D Ndarray

In [25]:
x = np.array([[[[12, 34, 45, 56], [34, 45, 65, 78]], [[34, 45, 3, 23], [45, 3, 23, 12]]], [[[12, 34, 45, 56], [34, 45, 65, 78]], [[34, 45, 3, 23], [45, 3, 23, 12]]]])

In [26]:
x

array([[[[12, 34, 45, 56],
         [34, 45, 65, 78]],

        [[34, 45,  3, 23],
         [45,  3, 23, 12]]],


       [[[12, 34, 45, 56],
         [34, 45, 65, 78]],

        [[34, 45,  3, 23],
         [45,  3, 23, 12]]]])

In [27]:
x.ndim

4

In [28]:
x.shape

(2, 2, 2, 4)

## Indexing or Slicing in ndarray

In [29]:
x = np.array([12, 34, 45, 67, 45, 34, 56, 10])

In [30]:
x

array([12, 34, 45, 67, 45, 34, 56, 10])

In [ ]:
# to get any element using index numberer....
objename[indexnumber]

In [33]:
x[6]

56

In [ ]:
postive indexing start from :   0, 1, 2, 3, ...... n
negtive indexing starts form :  -1, -2, -3, -4,  ........ -n

In [34]:
x = np.array([12, 34, 45, 67, 45, 34, 56, 10])

In [36]:
x[-2]

56

In [37]:
x[3]

67

In [38]:
x[-5]

67

### indexing with 2-D ndarray:

In [40]:
zx = np.array([[12, 23, 4, 56, 67, 34, 23], [34, 45, 67, 7, 5, 34, 23]])

In [43]:
zx

array([[12, 23,  4, 56, 67, 34, 23],
       [34, 45, 67,  7,  5, 34, 23]])

In [44]:
# obname[arrayindex][elementindex]

In [50]:
pq = zx[1]

In [51]:
pq[6]

23

In [52]:
zx[1][-1]

23

In [53]:
zx = np.array([[12, 23, 4, 56, 67, 34, 23], [34, 45, 67, 7, 5, 34, 23], [12, 3, 45, 23, 45, 23, 45]])

In [54]:
zx

array([[12, 23,  4, 56, 67, 34, 23],
       [34, 45, 67,  7,  5, 34, 23],
       [12,  3, 45, 23, 45, 23, 45]])

In [55]:
zx.shape

(3, 7)

In [56]:
zx[2][1]

3

In [57]:
# indexing with 3-D

In [61]:
qw = np.array([[[12, 34, 45, 34], [34, 45, 67, 4]], [[34, 56, 78, 56], [45, 89, 67, 56]]])

In [62]:
qw

array([[[12, 34, 45, 34],
        [34, 45, 67,  4]],

       [[34, 56, 78, 56],
        [45, 89, 67, 56]]])

In [65]:
qw[1][1][1]

89

In [66]:
# Slicing : 

In [67]:
zx = np.array([12, 2, 4, 56, 67, 78, 89])

In [68]:
zx[4]

67

In [ ]:
objectname[start : end : incremet]

default values:
    start : 0
    end : n - 1
    increment : 1

In [70]:
zx[2 : -2]

array([ 4, 56, 67])

In [72]:
# for i in range(1, 11):
#     print(i)

In [73]:
zx = np.array([12, 2, 4, 56, 67, 78, 89])

In [75]:
zx[ : 5]

array([12,  2,  4, 56, 67])

In [76]:
zx[3 : ]

array([56, 67, 78, 89])

In [81]:
zx = np.array([12, 2, 4, 56, 67, 78, 89, 45, 78, 34, 34, 45, 23])

In [82]:
zx[ : : 2]

array([12,  4, 67, 89, 78, 34, 23])

In [83]:
zx = np.array([12, 2, 4, 56, 67, 78, 89, 45, 78, 34, 34, 45, 23])

In [84]:
# reverse ndarray

In [85]:
zx[: : -1]

array([23, 45, 34, 34, 78, 45, 89, 78, 67, 56,  4,  2, 12])

In [86]:
# 2-d slicing

In [87]:
pq = np.array([[12, 23, 4, 45, 56], [34, 5, 67, 78, 34]])

In [88]:
# objename[arrayindex][slcing]

In [90]:
pq[1][1 : 4]

array([ 5, 67, 78])

In [91]:
pq[0][2 : ]

array([ 4, 45, 56])

In [92]:
qw = np.array([[[12, 34, 45, 34], [34, 45, 67, 4]], [[34, 56, 78, 56], [45, 89, 67, 56]]])

In [93]:
qw

array([[[12, 34, 45, 34],
        [34, 45, 67,  4]],

       [[34, 56, 78, 56],
        [45, 89, 67, 56]]])

In [97]:
qw[1][0][1 : ]

array([56, 78, 56])

In [99]:
qw[0][0][0 : -1]

array([12, 34, 45])

In [100]:
# this is 100

In [ ]:
numpy
ndarray
ndim
shape
indxing
slicing