In [1]:
# (Xt.X)-1 . Xt.Y

In [2]:
# x --> x_train
# y --> y_train

In [3]:
import pandas as pd

In [4]:
data = pd.read_csv("empp dataset.csv")

In [5]:
data

age  experience  income
0    25           1   30450
1    30           3   35670
2    47           2   31580
3    32           5   40130
4    43          10   47830
5    51           7   41630
6    28           5   41340
7    33           4   37650
8    37           5   40250
9    39           8   45150
10   29           1   27840
11   47           9   46110
12   54           5   36720
13   51           4   34800
14   44          12   51300
15   41           6   38900
16   58          17   63600
17   23           1   30870
18   44           9   44190
19   37          10   48700

In [8]:
x = data.iloc[:, 0:2]
x

age  experience
0    25           1
1    30           3
2    47           2
3    32           5
4    43          10
5    51           7
6    28           5
7    33           4
8    37           5
9    39           8
10   29           1
11   47           9
12   54           5
13   51           4
14   44          12
15   41           6
16   58          17
17   23           1
18   44           9
19   37          10

In [10]:
y = data.iloc[:, -1]
y

0     30450
1     35670
2     31580
3     40130
4     47830
5     41630
6     41340
7     37650
8     40250
9     45150
10    27840
11    46110
12    36720
13    34800
14    51300
15    38900
16    63600
17    30870
18    44190
19    48700
Name: income, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [12]:
data.shape

(20, 3)

In [13]:
x_train.shape

(16, 2)

In [14]:
x_test.shape

(4, 2)

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
obj = LinearRegression()

In [17]:
obj.fit(x_train, y_train)

LinearRegression()

In [18]:
obj.intercept_

31685.445910788083

In [19]:
obj.coef_

array([-107.31625074, 2171.05425156])

In [20]:
# y = b0 + b1x1 + b2x2

In [21]:
y = 31685.445910788083 + (-107.31625074*26) + 2171.05425156 * 4

In [22]:
y

37579.44039778809

In [23]:
y_pred = obj.predict(x_test)

In [28]:
from sklearn.metrics import r2_score

In [29]:
r2_score(y_test, y_pred)

0.9561190023324804

In [30]:
# (Xt.X)-1 . Xt.Y

In [71]:
class mymultiplelinearregALgo:
    def __init__(self):
        self.cofi = None
        self.intecept = None

    def fit(self, x_train, y_train):
        # (Xt.X)-1 . Xt.Y 
        x_train_new = np.insert(x_train, 0, 1, axis = 1)

        # use formula
        np.linalg.inv(np.dot(x_train_new.T, x_train_new)).dot(x_train_new.T).dot(y_train)

    

    def predict(sef, x_test):
        pass

In [72]:
mymodel = mymultiplelinearregALgo()

In [73]:
mymodel.fit(x_train, y_train)

In [41]:
import numpy as np

In [44]:
x_train_new = np.insert(x_train, 0, 1, axis = 1)

array([[ 1, 32,  5],
       [ 1, 39,  8],
       [ 1, 47,  2],
       [ 1, 51,  4],
       [ 1, 25,  1],
       [ 1, 58, 17],
       [ 1, 37, 10],
       [ 1, 44,  9],
       [ 1, 37,  5],
       [ 1, 47,  9],
       [ 1, 54,  5],
       [ 1, 41,  6],
       [ 1, 43, 10],
       [ 1, 51,  7],
       [ 1, 28,  5],
       [ 1, 23,  1]], dtype=int64)

In [45]:
x_train_new = np.insert(x_train, 0, 1, axis = 1)

In [49]:
x_train_new.T

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [32, 39, 47, 51, 25, 58, 37, 44, 37, 47, 54, 41, 43, 51, 28, 23],
       [ 5,  8,  2,  4,  1, 17, 10,  9,  5,  9,  5,  6, 10,  7,  5,  1]],
      dtype=int64)

In [50]:
# metrix multiplication

In [59]:
x = np.array([[2, 4], [3, 4]])
x

array([[2, 4],
       [3, 4]])

In [61]:
y = np.array([[3, 2], [2, 3]])
y

array([[3, 2],
       [2, 3]])

In [62]:
np.dot(x, y)

array([[14, 16],
       [17, 18]])

In [63]:
# calculate inverse
y = np.array([[3, 2], [2, 3]])


In [64]:
np.linalg.inv(y)

array([[ 0.6, -0.4],
       [-0.4,  0.6]])